# Generated by Django 4.1.5 on 2023-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('roll_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('mobile_no', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
