# Generated by Django 4.1.5 on 2023-01-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='School_App.usertype'),
        ),
    ]
