# Generated by Django 4.1.5 on 2023-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to='media/userprofile/'),
        ),
    ]
