# Generated by Django 4.1.5 on 2023-01-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default='default.png', upload_to='media/userprofile/'),
        ),
    ]
