# Generated by Django 4.1.5 on 2023-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0008_alter_user_address_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.CharField(choices=[('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default='9th', max_length=20),
        ),
    ]
