# Generated by Django 4.1.5 on 2023-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0009_user_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
