# Generated by Django 4.1.5 on 2023-01-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0010_alter_user_bloodgroup_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
