# Generated by Django 4.1.5 on 2023-01-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0011_alter_user_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='')),
                ('subject_name', models.CharField(max_length=30)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_App.usertype')),
            ],
        ),
    ]
