# Generated by Django 4.1.5 on 2023-01-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0012_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='usertype',
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='School_App.user'),
        ),
    ]
