# Generated by Django 4.1.5 on 2023-01-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0017_rename_per_result_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(default='default.png', upload_to='assignment/'),
        ),
    ]
