# Generated by Django 4.1.5 on 2023-01-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0018_alter_assignment_assignment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start',
            new_name='start_date',
        ),
    ]
